[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[lib]
name = "backend"
path = "src/lib.rs"

[[bin]]
name = "contact"
path = "api/contact.rs"

[[bin]]
name = "library"
path = "api/library.rs"

[dependencies]
yup-oauth2 = { version = "12", features = ["service-account"] }
axum = "0.8.9"
chrono = "0.4.44"
google-sheets4 = "7.0.0"
http = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
tower = "0.5.3"
tower-http = { version = "0.6.10", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
validator = "0.16.1"
vercel_runtime = { version = "2.4.0", features = ["axum"] }
webhook = "2.1.2"
base64 = "0.23.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
