[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "contact"
path = "api/contact.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
vercel_runtime = { version = "2" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
